### ISSUE TITLE
Can't type same capital and lower letters alternately

### ISSUE THREAD

**Issue by hrtshu** [dbw9580/BridgeTooth#1]
Thank you for awesome plugin for Keepass2Android.
I've wanted this for a long time.

I found a bug that I can't type same capital and lower letters alternately.

For example:
- (real input) -> (result)
- "**a**A" -> "a"
- "**A**a" -> "A"
- "**b**Bb" -> "b"
- "**B**bBbBb" -> "B"
- "**c**C**C**cC" -> "cC"
- "**DDD**dD**D**" -> "DDDD"
- "**DDDDD**" -> DDDDD

My environment:
- PC
  - Model: Dell Inspiron
  - OS: Windows 10 Pro 1809
- Phone
  - Model: Huawei P20 Pro
  - OS: Android 8.1.0
  - Note: APK file was downloaded from https://github.com/dbw9580/BridgeTooth/releases/download/v0.0.1/v0.0.1-debug.apk

**Comment by dbw9580** [comment]
Fixed in 0a09c1b. Please verify if it is working in debug release 2. 
You may have to uninstall then reinstall the app, and disable then re-enable it from within Keepass2Android.

**Comment by hrtshu** [comment]
I could verify that it works correctly.
Thank you for fixing quickly.
